version: '3'

services:
  web:
    restart: always
    build: ./blog
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./blog:/usr/src/blog
      - ./blog/static:/usr/src/blog/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn blog.wsgi:application -w 2 -b :8000
  migration:
    build: ./blog
    image: web
    command: bash init_app.sh
    volumes:
      - ./blog:/usr/src/blog
    links:
      - postgres
    depends_on:
      - postgres
    env_file: .env
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./blog/static:/www/static
    links:
      - web:web
  postgres:
    restart: always
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/


volumes:
  web-django:
  web-static:
  pgdata:
  redisdata: